### ISSUE TITLE
Series A checklist 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/.github#63]
The goal is a successful series A in about 10-16 months

- [ ] Ubiquity Dollar launch with collateral
- [ ] Integration of the Ubiquity Dollar with DevPool 
- [ ] Liquidity for Ubiquity Dollar 
- [ ] The launch of UbiquiCards

**Comment by sergfeldman** [comment]
A proposal 
https://github.com/orgs/ubiquity/discussions/47

**Comment by sergfeldman** [comment]
Integration of Ubiquity with DevPool
https://github.com/ubiquity/.github/issues/66
