### ISSUE TITLE
Q1 2024 Priorities

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/.github#93]
### TOP PRIORITIES
- [x] get payment permits to work (deadline 1 January) 
   - pavlovcik
   - wannacfuture
   - whilefoo
- [x] hire two developers for korea office (deadline 1 March) https://github.com/ubiquity/recruiting/issues/3
   - diamondnegroni
- [x] implement sherlock audit fixes (deadline 1 April) https://github.com/ubiquity/ubiquity-dollar/issues/874 https://github.com/ubiquity/ubiquity-dollar/issues/866 https://github.com/ubiquity/ubiquity-dollar/issues/835
   - rndquu
   - molecula451
   - gitcoindev
### NEXT PRIORITIES
- [ ] research prepaid card API / implement prototype (deadline 1 March) https://github.com/ubiquity/card-issuance/issues/34
   - rndquu
   - WhileFoo 
   - sergfeldman
- [ ] migrate to bot kernel + break apart all handlers to plugins https://github.com/ubiquity/ubiquibot/issues/906
   - pavlovcik
   - wannacfuture
   - WhileFoo
- [ ] dedicated payment permit generation endpoint
   - WhileFoo
- [ ] vector embeddings https://github.com/ubiquibot/comment-incentives/issues/9
   - ?

**Comment by molecula451** [comment]
we are awaiting for them (sherklok) to updates us on their side, no new words yet, so the PR, reviewing season about to begin again

**Comment by pavlovcik** [comment]
My perspective on completedness:

> ### TOP PRIORITIES
> * [x]  get payment permits to work (deadline 1 January) 

100%

> * [ ]  hire two developers for korea office (deadline 1 March) [Hire two (or more) talented TypeScript developers recruiting#3](https://github.com/ubiquity/recruiting/issues/3)

80%

> * [ ]  implement sherlock audit fixes (deadline 1 April) [Audit: fix low severity issues ubiquity-dollar#874](https://github.com/ubiquity/ubiquity-dollar/issues/874) [Conquer the Enigma of Random Crashes: Audit - must fix ubiquity-dollar#866](https://github.com/ubiquity/ubiquity-dollar/issues/866) [Road to production 2023 ubiquity-dollar#835](https://github.com/ubiquity/ubiquity-dollar/issues/835)

90%

> ### NEXT PRIORITIES
> * [ ]  research prepaid card API / implement prototype (deadline 1 March) [Bounty proposal: integrate Reloadly API card-issuance#34](https://github.com/ubiquity/card-issuance/issues/34)

? @rndquu rfc

> * [ ]  migrate to bot kernel + break apart all handlers to plugins [Plugin Config Proposal ubiquibot#906](https://github.com/ubiquity/ubiquibot/issues/906)

50%

> * [ ]  dedicated payment permit generation endpoint

0%

> * [ ]  vector embeddings [Qualitative Analysis v2 ubiquibot/comment-incentives#9](https://github.com/ubiquibot/comment-incentives/issues/9)

0%

**Comment by rndquu** [comment]
> research prepaid card API / implement prototype (deadline 1 March)

Yes, it's 90% ready, I think that the issue for a new pay.ubq.fi backend service (that is intended to work with https://github.com/ubiquity/pay.ubq.fi/issues/174) will be ready today

**Comment by rndquu** [comment]
> > Yes, it's 90% ready,
> 
> How long do you think until we can issue cards for the fundraising team from Stripe?

I think we can make it simple:
1. Ask stripe to enable live mode for card issuing
2. Use stripe's dashboard and create a new card for somebody with US residence (need to find such person)
3. Try to pay with the issued card in South Korea

If everything is fine then we're good to proceed with physical cards (again, issue to somebody with US residence but somehow deliver to South Korea)

**Comment by pavlovcik** [comment]
> Ask stripe to enable live mode for card issuing

They seem to have ignored my requests I'll keep following up. 

> If everything is fine then we're good to proceed with physical cards (again, issue to somebody with US residence but somehow deliver to South Korea)

I can get it done pretty easily.
